[build]
  publish = "./"
  command = "node netlify-build.js"
  ignore = "git diff --quiet HEAD^ HEAD -- '*.js' '*.html' '*.css' '*.toml' 'assets/**' && git diff --quiet HEAD^ HEAD -- '!*.py' '!requirements.txt'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  API_URL = "https://bioflow.onrender.com"
  PYTHON_USED = "false"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 